# Example values to expose Coturn on a custom NodePort and domain.

hostNetwork: false

service:
  enabled: true
  type: NodePort
  ports:
    - name: turn-udp
      port: 3478
      protocol: UDP
      targetPort: 3478
      nodePort: 31192
    - name: turn-tcp
      port: 3478
      protocol: TCP
      targetPort: 3478
      nodePort: 31192
    - name: turn-tls-udp
      port: 5349
      protocol: UDP
      targetPort: 5349
    - name: turn-tls-tcp
      port: 5349
      protocol: TCP
      targetPort: 5349

turnserver:
  config: |
    listening-port=3478
    tls-listening-port=5349
    fingerprint
    no-cli
    use-auth-secret
    static-auth-secret=$(STATIC_AUTH_SECRET)
    realm=turn.server.ghifari.dev
  extraArgs:
    - --log-file=stdout
    - --min-port=49160
    - --max-port=49200
  extraEnv:
    - name: STATIC_AUTH_SECRET
      valueFrom:
        secretKeyRef:
          name: coturn-rest-secret
          key: sharedSecret

tls:
  enabled: true
  secretName: turn-server-ghifari-dev-tls
  certFile: /coturn/tls/tls.crt
  keyFile: /coturn/tls/tls.key
